CREATE SEQUENCE SEQ_USER
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE SEQ_BOOK
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE TABLE TBL_USER(
 	user_number NUMBER,
 	user_name varchar2(100) NOT NULL,
 	user_phonenumber varchar2(100) NOT NULL,
 	USER_id varchar2(100) NOT NULL,
 	user_pw varchar2(100) NOT NULL,
 	CONSTRAINT PK_USER_NUMBER PRIMARY key(user_number),
 	CONSTRAINT UK_USER_ID UNIQUE (USER_ID)
);

CREATE TABLE TBL_BOOKS(
	BOOK_NUMBER NUMBER,
	BOOK_TITLE varchar2(100) NOT NULL,
	BOOK_AUTHOR varchar2(100) NOT NULL,
	BOOK_AVAILABLE Char(1) DEFAULT 'T' NOT NULL,
	USER_NUMBER NUMBER,
	CONSTRAINT PK_BOOK_NUMBER PRIMARY KEY(book_number),
	CONSTRAINT FK_USER_NUMBER FOREIGN KEY(USER_NUMBER) REFERENCES TBL_USER (USER_NUMBER),
	CHECK(BOOK_AVAILABLE IN ('T', 'F'))
);

INSERT INTO TBL_BOOKS (BOOK_NUMBER, BOOK_TITLE, BOOK_AUTHOR)
--VALUES (0, '자바', '짱구');
--VALUES (1, 'DB', '훈이');
--VALUES (2, '게임학개론', '맹구');
--VALUES (3, '공포소설', '철수');
--VALUES (4, '전쟁소설', '유리');

--DROP TABLE TBL_BOOKS;
--DROP TABLE TBL_USER;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOOKS;
